import json,pathlib,sys,datetime
run=sys.argv[1]
def seconds(t):return datetime.datetime.fromisoformat(t.replace('Z','+00:00')).timestamp()
def read(name):
 p=pathlib.Path('runs')/name;r=[json.loads(x) for x in (p/'events.jsonl').read_text().splitlines()];v=json.loads((p/'verification.json').read_text());d=[x for x in r if x['type']=='decision'];plans=[x for x in r if x['type']=='plan'];start=next(x for x in r if x['type']=='recording_started');won=next(x for x in r if x['type']=='game_won');return dict(run=name,videoSeconds=float(v['media']['format']['duration']),exitPortalSeconds=round(seconds(won['time'])-seconds(start['time']),2),decisions=len(d),plannerCalls=len(plans),boatDecisions=sum(x['selected'].startswith('row_') for x in d),genericWaits=sum(x['selected']=='wait' for x in d),failures=sum(x['type']=='result' and str(x.get('result','')).startswith('FAILED') for x in r),deaths=v['deathCount'],plannerModels=v['plannerModels'],controllerModels=v['controllerModels'],passed=v['passed'])
a,b=read('optimized-final-04'),read(run);assert b['passed'];out={'previous':a,'new':b,'videoReductionPercent':round((1-b['videoSeconds']/a['videoSeconds'])*100,1),'timeToExitReductionPercent':round((1-b['exitPortalSeconds']/a['exitPortalSeconds'])*100,1)};pathlib.Path('optimization/pass-2/comparison.json').write_text(json.dumps(out,indent=2))
def fmt(x):return f'{int(x)//60}m {int(x)%60:02d}s'
lines=['# Second-pass result','','| Measure | Previous run | New run |','|---|---:|---:|']
for key,label in [('videoSeconds','Full video'),('exitPortalSeconds','Exit portal reached'),('decisions','JEV decisions'),('plannerCalls','Planner calls'),('boatDecisions','Boat decisions'),('genericWaits','Generic waits'),('failures','Action failures'),('deaths','Deaths')]:lines.append(f'| {label} | {fmt(a[key]) if key.endswith("Seconds") else a[key]} | {fmt(b[key]) if key.endswith("Seconds") else b[key]} |')
lines+=['','The previous planner was Sol. The new planner is Astra. JEV controls both runs. Both use Survival/Peaceful and the same seed. This compares two full systems and single runs, not model quality in isolation. Path searches that make useful progress are now reported as progress, so failure counts also reflect that change.','',f'The new run is `{run}`. All gameplay was recorded from an empty inventory through the dragon kill and exit portal. Source and guidance hashes stayed unchanged during the run.','', 'The full native capture is retained. The annotated video adds model objectives, selected actions, API latency, elapsed time, stage, supplies, and position in a strip above the complete game image. It has no audio.','', 'See `REVIEW.md` for the transcript findings, isolated scenarios, and the failed preparation test that exposed the missing bed-search choice.']
pathlib.Path('optimization/pass-2/RESULT.md').write_text('\n'.join(lines)+'\n');print(json.dumps(out,indent=2))
