// Prepared scenarios on port 25577 only. Never connects to the full-run server.
import fs from 'node:fs';import {spawn} from 'node:child_process';import mineflayer from 'mineflayer';import pf from 'mineflayer-pathfinder';import {Vec3} from 'vec3';import {installBoat} from '../../boat.mjs';import {installBoat as oldBoat} from '../../runs/optimized-final-04/source/boat.mjs';import {approachEndCover} from '../../navigation.mjs';import {decide} from '../../models.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),root='scenario-pass2',results=process.env.SKIP_BOAT?JSON.parse(fs.readFileSync('optimization/pass-2/boat-results.json')):[];
const java=(()=>{if(!process.env.MC_JAVA_HOME)throw Error('Set MC_JAVA_HOME to a Java 17 installation');return process.env.MC_JAVA_HOME+'/bin/java';})();
const server=spawn(java,['-Xms256M','-Xmx1G','-jar','server.jar','nogui'],{cwd:root,stdio:['pipe','pipe','pipe']});const log=fs.createWriteStream(root+'/scenario-server.log');server.stdout.pipe(log);server.stderr.pipe(log);
let bot;const cmd=async(s,ms=300)=>{server.stdin.write(s+'\n');await sleep(ms);};
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout')),60000);server.stdout.on('data',b=>{if(b.toString().includes('Done (')){clearTimeout(timer);resolve();}});});
 for(const [label,install] of (process.env.SKIP_BOAT?[]:[['previous',oldBoat],['revised',installBoat]])){
  bot=mineflayer.createBot({host:'127.0.0.1',port:25577,username:'ScenarioBot',version:'1.16.5'});bot.loadPlugin(pf.pathfinder);const boat=install(bot);await new Promise(r=>bot.once('spawn',r));bot.pathfinder.setMovements(new pf.Movements(bot));
  await cmd('kill @e[type=minecraft:boat]');await cmd('execute in minecraft:overworld run tp ScenarioBot 2.5 64 4.5',800);await bot.waitForChunksToLoad();
  await cmd('forceload add 0 0 140 8',2000);
  for(const c of ['fill 0 62 0 140 62 8 stone','fill 0 63 0 140 63 8 water','fill 0 64 0 140 75 8 air','clear ScenarioBot','give ScenarioBot minecraft:oak_boat 1'])await cmd(c);
  await cmd('tp ScenarioBot 2.5 64 4.5',1000);await bot.waitForTicks(10);
  console.log('fixture',JSON.stringify({position:bot.entity.position,water:bot.findBlocks({matching:b=>b.name==='water',maxDistance:5,count:20}).map(p=>({p,props:bot.blockAt(p).getProperties()})),site:boat.placementSite({x:100,z:4.5})}));
  await boat.place({x:100,z:4.5});const start=Date.now();let calls=0;const samples=[];
  while(Math.hypot(bot.entity.position.x-100,bot.entity.position.z-4.5)>5&&calls<12){const route=boat.routes({x:100,z:4.5})[0];const action={key:'row',description:`Row along ${route.distance} observed clear water blocks toward X100 Z4.5`,fn:()=>boat.drive(route.target,20000)};const choice=await decide({scenario:'Prepared boat lane; reach X100 Z4.5',position:bot.entity.position,health:bot.health},[action]);const r=await choice.selected.fn();samples.push({result:r,position:bot.entity.position.clone(),model:choice.data.model});calls++;}
  if(Math.hypot(bot.entity.position.x-100,bot.entity.position.z-4.5)>5)throw Error('Boat did not reach target');results.push({scenario:'100-block boat lane',version:label,seconds:(Date.now()-start)/1000,jevDecisions:calls,samples});console.log(JSON.stringify(results.at(-1)));await boat.dismount();bot.quit();await sleep(500);
 }
 bot=mineflayer.createBot({host:'127.0.0.1',port:25577,username:'ScenarioBot',version:'1.16.5'});bot.loadPlugin(pf.pathfinder);await new Promise(r=>bot.once('spawn',r));const movements=new pf.Movements(bot);movements.allowParkour=false;movements.maxDropDown=3;bot.pathfinder.setMovements(movements);bot.pathfinder.thinkTimeout=3000;
 await cmd('give ScenarioBot minecraft:stone_pickaxe 1');await cmd('give ScenarioBot minecraft:dirt 32');await cmd('execute in minecraft:the_end run forceload add -16 -16 112 16',2000);await cmd('execute in minecraft:the_end run fill -3 60 -3 3 60 3 air replace minecraft:end_portal',500);await cmd('execute in minecraft:the_end run tp ScenarioBot 100.5 49 0.5',1000);await bot.waitForChunksToLoad().catch(()=>{if(!bot.blockAt(bot.entity.position.offset(0,-1,0)))throw Error('Local End terrain unavailable');});
 const bounded=async(p,ms)=>{let t;try{return await Promise.race([p,new Promise((_,reject)=>{t=setTimeout(()=>{bot.pathfinder.setGoal(null);reject(Error('Action timeout'));},ms);})]);}finally{clearTimeout(t);}};
 const before=Date.now();let failure=null;try{await bounded(bot.pathfinder.goto(new pf.goals.GoalBlock(-1,60,0)),15000);}catch(e){failure=e.message;}bot.pathfinder.setGoal(null);results.push({scenario:'End approach',version:'previous',seconds:(Date.now()-before)/1000,failure,position:bot.entity.position.clone()});console.log(JSON.stringify(results.at(-1)));
 await cmd('execute in minecraft:the_end run tp ScenarioBot 100.5 49 0.5',1000);const start=Date.now();let calls=0;const outcomes=[];while(bot.entity.position.distanceTo(new Vec3(-.5,60,.5))>1&&calls<8){const a={key:'approach',description:'Follow one short, loaded segment toward End cover',fn:()=>approachEndCover(bot,new Vec3(-1,60,0),bounded)};const choice=await decide({scenario:'Prepared End movement test; dragon was already defeated in copied world',position:bot.entity.position,health:bot.health},[a]);outcomes.push(await choice.selected.fn());calls++;console.log('segment',calls,bot.game.dimension,JSON.stringify(bot.entity.position),outcomes.at(-1));}if(bot.entity.position.distanceTo(new Vec3(-.5,60,.5))>1)throw Error('Cover not reached');results.push({scenario:'End approach',version:'revised',seconds:(Date.now()-start)/1000,jevDecisions:calls,outcomes,position:bot.entity.position.clone()});console.log(JSON.stringify(results.at(-1)));
 fs.writeFileSync('optimization/pass-2/scenario-results.json',JSON.stringify({preparedTestOnly:true,world:'copy of completed world; artificial boat lane; supplied test items and positions; no full-run evidence',results,passed:true},null,2));
}finally{bot?.quit();await cmd('stop',500);}
