// Prepared test world only. This program cannot connect to the Survival server.
import mineflayer from 'mineflayer';import pf from 'mineflayer-pathfinder';import {endCombatActions} from './end-combat.mjs';import http from 'node:http';import {Vec3} from 'vec3';import {battleObservation,updateDragonSensor} from './extra-actions.mjs';
const bot=mineflayer.createBot({host:'127.0.0.1',port:25577,username:'LabBot',version:'1.16.5'});
bot.loadPlugin(pf.pathfinder);bot.once('spawn',()=>bot.pathfinder.setMovements(new pf.Movements(bot)));
const bounded=(promise,ms=18000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>{bot.pathfinder.setGoal(null);reject(new Error('timeout'));},ms))]);
const go=(p,r=1)=>bounded(bot.pathfinder.goto(new pf.goals.GoalNear(p.x,p.y,p.z,r)));
setInterval(async()=>{try{updateDragonSensor(await(await fetch('http://127.0.0.1:3092')).json());}catch{}},50);
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');let actions=[];endCombatActions(bot,(key,description,fn)=>actions.push({key,description,fn}),{go,bounded,item:n=>bot.inventory.items().find(i=>i.name===n)});let result;if(u.pathname==='/do'){const act=actions.find(a=>a.key===u.searchParams.get('key'));if(!act)throw new Error('Unknown action');result=await act.fn();}if(u.pathname==='/place'){const [x,y,z]=['x','y','z'].map(k=>Number(u.searchParams.get(k)));let ref=bot.blockAt(new Vec3(x,y,z));await bot.equip(bot.inventory.items().find(i=>i.name.endsWith('_bed')),'hand');await bot.look(Number(u.searchParams.get('yaw')||0),0,true);await bot.waitForTicks(3);await bot._placeBlockWithOptions(ref,new Vec3(0,1,0),{forceLook:'ignore'});}if(u.pathname==='/blast'){let b=bot.findBlock({matching:b=>b.name.endsWith('_bed'),maxDistance:12});await bot.activateBlock(b);await bot.waitForTicks(15);}res.end(JSON.stringify({result,actions:actions.map(({key,description})=>({key,description})),dimension:bot.game?.dimension,entities:Object.values(bot.entities).map(e=>e.name),p:bot.entity?.position,health:bot.health,battle:battleObservation(bot),beds:bot.findBlocks({matching:b=>b.name.endsWith('_bed'),maxDistance:16,count:8}).map(p=>({p,props:bot.blockAt(p).getProperties()}))}));}catch(e){res.statusCode=500;res.end(e.message);}}).listen(3091,'127.0.0.1');
bot.on('error',console.error);
