// Build an accurate display strip from timestamped model and game events.
// The complete, unmodified native capture is retained beside the output.
import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import {createCanvas,registerFont} from 'canvas';import {plannerLabel} from './models.mjs';
const fonts=process.platform==='win32'?(process.env.WINDIR||'C:\\Windows')+'\\Fonts\\':null;registerFont(fonts?fonts+'arial.ttf':'/System/Library/Fonts/Supplemental/Arial.ttf',{family:'Overlay'});registerFont(fonts?fonts+'arialbd.ttf':'/System/Library/Fonts/Supplemental/Arial Bold.ttf',{family:'Overlay',weight:'bold'});
const run=process.argv[2];if(!run)throw Error('Usage: node overlay.mjs RUN [preview-seconds]');const dir=path.resolve('runs',run),source=path.join(dir,'full-playthrough.mp4'),testSeconds=Number(process.env.OVERLAY_TEST_SECONDS||0),offset=Number(process.env.OVERLAY_TEST_START||0),out=path.join(dir,testSeconds?'overlay-test.mp4':'full-playthrough-overlay.mp4');
const events=fs.readFileSync(path.join(dir,'events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);const started=events.find(e=>e.type==='recording_started');const zero=Date.parse(started.time);const media=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration:stream=width,height','-of','json',source],{encoding:'utf8'}));const duration=testSeconds||Number(media.format.duration),width=960,bandHeight=120;
const config=JSON.parse(fs.readFileSync(path.join(dir,'run-config.json')));const modelName=plannerLabel(config.planner).toUpperCase();const timeline=events.map(e=>({...e,at:(Date.parse(e.time)-zero)/1000})).sort((a,b)=>a.at-b.at);
const canvas=createCanvas(width,bandHeight),g=canvas.getContext('2d');let index=0,state=events.find(e=>e.type==='start')?.state||{},objective='Waiting for the first plan',action='Waiting for the first action',step=0,apiMs=0,done=false,planMs=0;
function words(text,maxWidth,maxLines=3){const lines=[];let line='';for(const word of String(text).replace(/[\r\n]+/g,' ').split(' ')){const next=line?line+' '+word:word;if(g.measureText(next).width>maxWidth&&line){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);if(lines.length>maxLines){lines.length=maxLines;let last=lines.at(-1);while(g.measureText(last+'…').width>maxWidth)last=last.slice(0,-1);lines[maxLines-1]=last+'…';}return lines;}
function advance(t){while(index<timeline.length&&timeline[index].at<=t){const e=timeline[index++];if(e.type==='plan'){objective=e.result.objective;planMs=e.latencyMs||0;}if(e.type==='start')state=e.state;if(e.type==='display_state')state={...state,...e};if(e.type==='decision'){state={...state,...JSON.parse(e.request.state)};step=e.step+1;apiMs=e.latencyMs||0;const choice=e.response?.answers?.action?.choice;action=e.request.questions.action.criteria[choice]||e.selected;}if(e.type==='result'){state={...state,position:e.position,inventory:e.inventory};}if(e.type==='death'){state={...state,...e.state};action='Player died';}if(e.type==='dragon_killed'){state.dragonKilled=true;}if(e.type==='game_won'){done=true;state.won=true;action='Dragon defeated. Exit portal reached.';}}}
function draw(t){advance(t);g.fillStyle='#0e1520';g.fillRect(0,0,width,bandHeight);g.fillStyle='#253346';g.fillRect(478,12,1,76);g.fillRect(16,91,928,1);g.textBaseline='top';g.font='bold 12px Overlay';g.fillStyle='#7fd6e5';g.fillText(`${modelName} / PLANNER${planMs?'  ·  '+(planMs/1000).toFixed(1)+'s API':''}`,16,10);g.fillStyle='#efc88b';g.fillText(done?'RUN COMPLETE / GAME EVENT':`JEV 1.13 / ACTION ${step||'—'}${apiMs?'  ·  '+(apiMs/1000).toFixed(2)+'s API':''}`,494,10);g.font='15px Overlay';g.fillStyle='#f0f3f7';words(objective,446).forEach((l,i)=>g.fillText(l,16,30+i*18));words(action,450).forEach((l,i)=>g.fillText(l,494,30+i*18));g.font='bold 12px Overlay';g.fillStyle=done?'#8be0ad':'#aab9ca';const inv=state.inventory||{},beds=Object.entries(inv).filter(([k])=>k.endsWith('_bed')).reduce((a,[,n])=>a+n,0),p=state.position||{};const phase=done?'COMPLETE':state.dimension==='the_end'?'THE END':state.stage?.toUpperCase()||'PREPARE';const clock=`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;g.fillText(`${clock}  |  ${phase}  |  Survival / Peaceful  |  Beds ${beds}  |  Obsidian ${inv.obsidian||0}  |  XYZ ${[p.x,p.y,p.z].map(n=>Math.round(n||0)).join('  ')}`,16,101);return canvas;}
if(process.argv[3]!==undefined){const t=Number(process.argv[3]);draw(t);fs.writeFileSync(path.join(dir,'overlay-preview.png'),canvas.toBuffer('image/png'));console.log(path.join(dir,'overlay-preview.png'));process.exit();}
const band=path.join(dir,'model-overlay.mp4');const enc=spawn('ffmpeg',['-y','-v','error','-f','rawvideo','-pixel_format','bgra','-video_size','960x120','-framerate','2','-i','pipe:0','-an','-c:v','libx264','-preset','veryfast','-crf','18','-pix_fmt','yuv420p',band],{stdio:['pipe','ignore','inherit']});const ended=once(enc,'close');for(let i=0;i<Math.ceil(duration*2)+1;i++){if(!enc.stdin.write(draw(i/2+offset).toBuffer('raw')))await once(enc.stdin,'drain');}enc.stdin.end();if((await ended)[0]!==0)throw Error('Overlay encoder failed');
execFileSync('ffmpeg',['-y','-v','error','-ss',String(offset),'-i',source,'-i',band,'-filter_complex','[0:v]pad=960:660:0:120:color=0x0e1520[game];[game][1:v]overlay=0:0:repeatlast=1[out]','-map','[out]','-t',String(duration),'-r','20','-an','-c:v','libx264','-preset','veryfast','-crf','26','-pix_fmt','yuv420p','-movflags','+faststart',out],{stdio:'inherit'});
fs.writeFileSync(path.join(dir,testSeconds?'overlay-test-manifest.json':'overlay-manifest.json'),JSON.stringify({testOnly:!!testSeconds,sourceTimeOffset:offset,source:path.basename(source),output:path.basename(out),width:960,height:660,gameViewport:{x:0,y:120,width:960,height:540},durationSeconds:duration,overlayUpdateHz:2,sourceOfText:'Timestamped model responses and game events; no inferred model thoughts',timeMapping:'Source video time is unchanged',planner:config.planner,controller:config.controller},null,2));console.log(out);
