import {threats} from './hostile-defense.mjs';
import {tunnelTool} from './mining-tools.mjs';
import {walkingKeys} from './camera-control.mjs';
import {Vec3} from 'vec3';
const passable=b=>b&&b.boundingBox==='empty'&&!['lava','fire','soul_fire','water'].includes(b.name);
function safeToDig(bot,b){if(!b?.diggable)throw Error('Tunnel block cannot be mined');for(const d of [[1,0,0],[-1,0,0],[0,1,0],[0,0,1],[0,0,-1]])if(bot.blockAt(b.position.offset(...d))?.name==='lava')throw Error('Lava beside tunnel');}
async function mine(bot,b){if(passable(b))return;safeToDig(bot,b);const tool=tunnelTool(bot,b);if(!tool)throw Error('Tunnel requires a pickaxe');await bot.equip(tool,'hand');await bot.dig(b,true);await bot.waitForTicks(2);}
export async function tunnelStep(bot,target,log=()=>{},limit=4){
 bot.pathfinder.setGoal(null);bot.clearControlStates();await bot.waitForTicks(3);let count=0;const start=Date.now();
 bot.checkedTravelActive=true;try{while(count<limit&&Date.now()-start<15000){if(bot.emergencyTravelStop)throw Error('Breath interrupts travel');const close=threats(bot).find(e=>e.position.distanceTo(bot.entity.position)<(e.name==='piglin_brute'?14:8));if(close&&!bot.coveredTravelActive){bot.navigationThreat=close.id;log('navigation_yield_threat',{entity:close.id,name:close.name,position:bot.entity.position});return 'Stopped on the checked floor for nearby '+close.name;}const p=bot.entity.position.floored();if(!bot.entity.onGround||(p.y!==target.y&&!bot.checkedStairs))throw Error('Tunnel requires a stable floor at route height');const dx=Math.sign(target.x-p.x),dz=dx?0:Math.sign(target.z-p.z);if(!dx&&!dz)break;const dy=bot.checkedStairs?Math.sign(target.y-p.y):0;const next=p.offset(dx,dy,dz);bot.setControlState('sneak',true);
 if(dy<0)await mine(bot,bot.blockAt(next.offset(0,2,0)));if(dy>0)await mine(bot,bot.blockAt(p.offset(0,2,0)));await mine(bot,bot.blockAt(next.offset(0,1,0)));await mine(bot,bot.blockAt(next));const floor=bot.blockAt(next.offset(0,-1,0));if(floor?.boundingBox!=='block'){if(!passable(floor))throw Error('Unsafe tunnel floor');const floorPos=next.offset(0,-1,0);let ref,face;for(const d of [[-dx,0,-dz],[0,-1,0],[1,0,0],[-1,0,0],[0,0,1],[0,0,-1]]){const candidate=bot.blockAt(floorPos.offset(...d));if(candidate?.boundingBox==='block'){ref=candidate;face=new Vec3(-d[0],-d[1],-d[2]);break;}}if(!ref&&dy<0){const anchor=bot.blockAt(p.offset(0,-1,0)),support=bot.blockAt(p.offset(0,-2,0));const supportItem=['cobblestone','dirt','netherrack','blackstone','polished_blackstone_bricks','cracked_polished_blackstone_bricks','basalt','polished_basalt','end_stone'].map(n=>bot.inventory.items().find(i=>i.name===n&&(n!=='cobblestone'||i.count>48))).find(Boolean);if(anchor?.boundingBox==='block'&&passable(support)&&supportItem){await bot.equip(supportItem,'hand');await bot.placeBlock(anchor,new Vec3(0,-1,0));await bot.waitForTicks(2);ref=bot.blockAt(p.offset(0,-2,0));face=new Vec3(dx,0,dz);if(ref?.boundingBox!=='block')ref=null;}}if(!ref)throw Error('Missing tunnel foundation');const item=['cobblestone','dirt','netherrack','blackstone','polished_blackstone_bricks','cracked_polished_blackstone_bricks','basalt','polished_basalt','end_stone'].map(n=>bot.inventory.items().find(i=>i.name===n&&(n!=='cobblestone'||i.count>48))).find(Boolean);if(!item)throw Error('No tunnel floor material');await bot.equip(item,'hand');await bot.placeBlock(ref,face);await bot.waitForTicks(2);if(bot.blockAt(next.offset(0,-1,0))?.boundingBox!=='block')throw Error('Tunnel floor was not placed');}
 const exposed=threats(bot).find(e=>e.position.distanceTo(bot.entity.position)<8);
 if(exposed&&!bot.coveredTravelActive){bot.navigationThreat=exposed.id;bot.clearControlStates();if(bot.inventory.slots[45]?.name==='shield')bot.activateItem(true);await bot.lookAt(exposed.position.offset(0,1.4,0));return 'Stopped behind the opening for nearby '+exposed.name;}
 const dest=next.offset(.5,0,.5);await bot.lookAt(new Vec3(dest.x,bot.entity.position.y+1.62,dest.z));bot.setControlState('sneak',false);let reached=false;for(let tick=0;tick<40;tick++){if(bot.emergencyTravelStop)throw Error('Breath interrupts travel');const d=dest.minus(bot.entity.position),dist=Math.hypot(d.x,d.z);if(dist<(dy<0?.24:.18)){reached=true;break;}bot.setControlState('sneak',dy!==0||dist<.6);for(const [key,value] of Object.entries(walkingKeys(bot.entity.yaw,d.x,d.z)))bot.setControlState(key,value);if(dy>0)bot.setControlState('jump',true);await bot.waitForTicks(1);}bot.clearControlStates();await bot.waitForTicks(dy?10:4);for(let t=0;t<12&&!bot.entity.onGround;t++)await bot.waitForTicks(1);if(!reached||Math.abs(bot.entity.position.y-next.y)>.1||!bot.entity.position.floored().equals(next))throw Error('Tunnel walk did not reach its floor');count++;log('tunnel_step',{position:bot.entity.position});}
 }finally{bot.checkedTravelActive=false;bot.clearControlStates();}return 'Crossed '+count+' checked tunnel cells';
}
