import test from 'node:test';import assert from 'node:assert/strict';import {mouseAxis,MOUSE_RATE,MOUSE_ACCEL,walkingKeys,lookAhead,angleDelta} from '../../camera-control.mjs';
test('continuous turn obeys speed and acceleration limits and settles without reversal',()=>{let yaw=0,v=0;for(let n=0;n<300;n++){const a=mouseAxis(Math.PI-yaw,v,.02);assert.ok(Math.abs(a.velocity)<=MOUSE_RATE+1e-9);assert.ok(a.delta>=0);if(Math.abs(Math.PI-yaw)>.01)assert.ok(Math.abs(a.velocity-v)<=MOUSE_ACCEL*.02+1e-9);yaw+=a.delta;v=a.velocity;}assert.ok(Math.abs(Math.PI-yaw)<.004);});
test('walking keys are independent of camera heading',()=>{assert.deepEqual(walkingKeys(0,1,0),{forward:false,back:false,right:true,left:false});assert.deepEqual(walkingKeys(Math.PI/2,1,0),{forward:false,back:true,right:false,left:false});assert.deepEqual(walkingKeys(0,1,-1),{forward:true,back:false,right:true,left:false});});
test('look-ahead reduces alternating block-centre heading changes',()=>{const path=Array.from({length:40},(_,i)=>({x:Math.ceil(i/2),z:-Math.floor(i/2),toBreak:[],toPlace:[]}));let near=[],far=[];for(let i=0;i<30;i++){const p=path[i],rest=path.slice(i+1);near.push(Math.atan2(p.x-rest[0].x,p.z-rest[0].z));far.push(lookAhead(p,rest).yaw);}const swing=a=>a.slice(1).reduce((s,v,i)=>s+Math.abs(angleDelta(v,a[i])),0);assert.ok(swing(far)<swing(near)/3);});
import {EventEmitter} from 'node:events';import {installCameraControl} from '../../camera-control.mjs';
test('precise look settles with Minecraft sensitivity rounding',async()=>{const bot=new EventEmitter();bot.entity={yaw:0,pitch:0};bot.setControlState=()=>{};bot.look=async(yaw,pitch)=>{const quantum=.15*Math.PI/180;bot.entity.yaw+=Math.round((yaw-bot.entity.yaw)/quantum)*quantum;bot.entity.pitch+=Math.round((pitch-bot.entity.pitch)/quantum)*quantum;};installCameraControl(bot);let timeout;try{await Promise.race([(async()=>{for(const [yaw,pitch] of [[.37,-.1],[.398,.07],[-.055,.015]]){await bot.look(yaw,pitch);assert.ok(Math.hypot(angleDelta(yaw,bot.entity.yaw),pitch-bot.entity.pitch)<.0045);}})(),new Promise((_,reject)=>timeout=setTimeout(()=>reject(Error('Precise look stalled')),7000))]);}finally{clearTimeout(timeout);bot.emit('end');}});
import {Vec3} from 'vec3';
test('edge recentering waits for a turn and vertical aim keeps the current heading',async()=>{const bot=new EventEmitter();bot.entity={yaw:0,pitch:0,position:new Vec3(0,10,0),eyeHeight:1.62};const controls={};bot.setControlState=(k,v)=>{controls[k]=v;};bot.look=async(y,p)=>{bot.entity.yaw=y;bot.entity.pitch=p;};installCameraControl(bot);try{const turning=bot.look(Math.PI/2,0);bot.setControlState('forward',true);assert.equal(controls.forward,false);await turning;bot.setControlState('forward',true);assert.equal(controls.forward,true);const heading=bot.entity.yaw;await bot.lookAt(new Vec3(0,9,0));assert.ok(Math.abs(bot.entity.yaw-heading)<.001);}finally{bot.emit('end');}});
import {endSafeAim} from '../../camera-control.mjs';
test('End camera lowers the view before a large turn and avoids an exposed Enderman eye ray',()=>{const b={game:{dimension:'the_end'},entity:{position:new Vec3(0,0,0)},entities:{},world:{raycast:()=>null}};assert.deepEqual(endSafeAim(b,{yaw:Math.PI/2,pitch:0},{yaw:0,pitch:0}),{yaw:0,pitch:-.75});assert.deepEqual(endSafeAim(b,{yaw:Math.PI/2,pitch:0},{yaw:0,pitch:-.7}),{yaw:Math.PI/2,pitch:-.75});b.entities.e={name:'enderman',position:new Vec3(0,-.93,-5)};assert.equal(endSafeAim(b,{yaw:0,pitch:0},{yaw:0,pitch:0}).pitch,-.75);});

test('Peaceful End turns preserve upward bed aim',()=>{const target={yaw:Math.PI*1.5,pitch:1.3};assert.deepEqual(endSafeAim({game:{dimension:'the_end',difficulty:'peaceful'}},target,{yaw:0,pitch:1.3}),target);});
