import test from 'node:test';import assert from 'node:assert/strict';import {Vec3} from 'vec3';import {workshopActions} from '../../nether-workshop.mjs';import {tunnelTool,spareToolsReady} from '../../mining-tools.mjs';
function fixture(wood=true){const iron={name:'iron_pickaxe',durabilityUsed:151,type:4},table={position:new Vec3(1,118,0)};return {entity:{position:new Vec3(0,118,0)},inventory:{items:()=>[iron]},registry:{blocksByName:{crafting_table:{id:1}},itemsByName:{iron_pickaxe:{id:2},stone_pickaxe:{id:3},wooden_pickaxe:{id:4}}},findBlock:()=>table,recipesFor:id=>wood&&id===4?[{}]:[]};}
test('Worn iron with no stone uses a craftable wooden replacement',()=>{const options=[];const handled=workshopActions(fixture(),(...a)=>options.push(a),{inventory:()=>({iron_pickaxe:1,stick:2,oak_planks:9})});assert.equal(handled,true);assert.deepEqual(options.map(a=>a[0]),['workshop_wooden_pickaxe']);});
test('Unavailable repair does not suppress usable-tool travel',()=>{const options=[];assert.equal(workshopActions(fixture(false),(...a)=>options.push(a),{inventory:()=>({iron_pickaxe:1,stick:2})}),false);assert.equal(options.length,0);});
test('Netherrack uses wooden pick and preserves iron while iron-only ore does not',()=>{const wood={name:'wooden_pickaxe',type:4},iron={name:'iron_pickaxe',type:5},bot={inventory:{items:()=>[iron,wood]},pathfinder:{bestHarvestTool:()=>iron}};assert.equal(tunnelTool(bot,{harvestTools:{4:true,5:true}}),wood);assert.equal(tunnelTool(bot,{harvestTools:{5:true}}),iron);});

test('A nugget batch uses the nearby crafting table for nine-slot ingot recipes',async()=>{const bot=fixture(),table=bot.findBlock();bot.inventory.items=()=>[{name:'iron_pickaxe',durabilityUsed:0}];bot.registry.itemsByName.gold_ingot={id:8};let calls=[];bot.recipesFor=(id,meta,count,t)=>id===8&&t===table?[{id}]:[];bot.craft=async(r,count,t)=>calls.push({r,count,t});const options=[];assert.equal(workshopActions(bot,(...a)=>options.push(a),{inventory:()=>({iron_pickaxe:1,gold_nugget:94})}),true);assert.equal(options[0][0],'workshop_gold_ingot');await options[0][2]();assert.equal(calls[0].count,10);assert.equal(calls[0].t,table);});
test('A ready gold batch converts the remaining nuggets below one stack',()=>{const bot=fixture(),table=bot.findBlock();bot.goldBatchReady=true;bot.inventory.items=()=>[{name:'iron_pickaxe',durabilityUsed:0}];bot.registry.itemsByName.gold_ingot={id:8};bot.recipesFor=(id,meta,count,t)=>id===8&&t===table?[{}]:[];const options=[];workshopActions(bot,(...a)=>options.push(a),{inventory:()=>({iron_pickaxe:1,gold_nugget:27})});assert.equal(options[0][0],'workshop_gold_ingot');});

test('The departure kit includes a reserve for a long Nether barter session',()=>{assert.equal(spareToolsReady({stone_pickaxe:3,oak_planks:8,stick:8}),false);assert.equal(spareToolsReady({stone_axe:1,stone_pickaxe:3,oak_planks:64,stick:16,cobblestone:48}),true);assert.equal(spareToolsReady({stone_axe:1,stone_pickaxe:3,oak_planks:64,stick:16,cobblestone:47}),false);});
