import mineflayer from 'mineflayer';import pf from 'mineflayer-pathfinder';import viewer from 'prismarine-viewer';import {Vec3} from 'vec3';import http from 'node:http';import {writeFileSync,appendFileSync} from 'node:fs';import {extraActions} from '../extra-actions.mjs';import {decide} from '../models.mjs';
const b=mineflayer.createBot({host:'127.0.0.1',port:25577,username:'LabBot',version:'1.16.5'});b.loadPlugin(pf.pathfinder);let busy=false;
const item=n=>b.inventory.items().find(i=>i.name===n);const inv=()=>Object.fromEntries(b.inventory.items().map(i=>[i.name,b.inventory.items().filter(t=>t.name===i.name).reduce((s,t)=>s+t.count,0)]));
async function bounded(p,ms=10000){let t;try{return await Promise.race([p,new Promise((_,r)=>t=setTimeout(()=>{b.pathfinder.setGoal(null);r(new Error('timeout'));},ms))]);}finally{clearTimeout(t);}}
const go=(p,r=1,ms=10000)=>bounded(b.pathfinder.goto(new pf.goals.GoalNear(p.x,p.y,p.z,r)),ms);
const options=()=>{const a=[];extraActions(b,(key,description,fn)=>a.push({key,description,fn}),{go,item,inv,bounded});return a;};
const state=()=>{const d=Object.values(b.entities).find(e=>e.name==='ender_dragon');return {testOnly:true,position:b.entity?.position,health:b.health,dimension:b.game?.dimension,inventory:inv(),dragon:d?{id:d.id,position:d.position,yaw:d.yaw,headApprox:d.position.offset(Math.sin(d.yaw)*6.5,-1,Math.cos(d.yaw)*6.5),metadata:d.metadata}:null,bedrock:b.entity?b.findBlocks({matching:b.registry.blocksByName.bedrock.id,maxDistance:30,count:70}):[],actions:b.entity?options().map(({key,description})=>({key,description})):[]};};
b.on('error',console.error);b.on('spawn',async()=>{await b.waitForChunksToLoad();b.pathfinder.setMovements(new pf.Movements(b));if(!b.viewer)viewer.mineflayer(b,{port:3087,firstPerson:false,viewDistance:6});});
http.createServer(async(req,res)=>{try{if(req.method==='POST'){if(busy)throw new Error('busy');busy=true;const opts=options();const key=decodeURIComponent(req.url.slice(1));let a;if(key==='jev'){const r=await decide({...state(),plan:{objective:'Test the bed explosion technique in this prepared combat lab. Set obsidian support, take cover behind the central fountain, place bed only during a perch then detonate near the dragon head. Do not waste beds while dragon is far away.'}},opts);a=r.selected;appendFileSync('combat-lab/decisions.jsonl',JSON.stringify({state:state(),response:r.data,selected:a.key})+'\n');}else a=opts.find(o=>o.key===key);if(!a)throw new Error('unknown action');await a.fn();}res.end(JSON.stringify(state()));}catch(e){res.statusCode=500;res.end(JSON.stringify({error:e.message,state:state()}));}finally{busy=false;}}).listen(3088,'127.0.0.1');
setInterval(()=>{if(b.entity)writeFileSync('combat-lab/state.json',JSON.stringify(state(),null,2));},500);
